version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/config:/config
      - ./volumes/data:/data
      - ./volumes/etc/caddy:/etc/caddy